<a href="https://colab.research.google.com/github/PrashantSBasnet/L3_Sem2/blob/master/Week7/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
arr1 = np.array([

                 [1,2,3,4,5,6],
                 [4,5,6,7,8,9]

        ])

In [6]:
print (arr1)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [7]:
print (arr1.shape)

(2, 6)


In [9]:
arr2 = arr1.flatten() #converting into 1D array
print(arr2)

[1 2 3 4 5 6 4 5 6 7 8 9]


In [11]:
arr3 = arr1.reshape(3,4) #3 Rows and 4 Columns
print (arr3)  #2d array created

[[1 2 3 4]
 [5 6 4 5]
 [6 7 8 9]]


In [17]:
print (arr1.size)

12


In [21]:
#3D array with dimensions 2x2x3, denoting a shape where the array consists of 2 matrices, each matrix containing 2 rows and 3 columns.
arr4 = arr1.reshape(2,2,3) #creating 3D array. since 12 elements the product = 12
print (arr4)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


**Matrices**

 A matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as * (matrix multiplication) and ** (matrix power).

Suppose x is  a 2 dimensional array.

In [22]:
x = np.array ([
              [2,3,4,5,6],
              [7,8,9,10,11]
])

In [24]:
m = np.matrix(x)
print (m)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]


In [25]:
m = np.matrix('1 2 3 4; 5,6,7,8')
print (m)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
m2 = np.matrix('1 2 3; 5,6,7; 8,9,10')
print (m2)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]


In [28]:
print (np.diagonal(m2))

[ 1  6 10]


In [30]:
print (m.min())

1


**Matrix Addition and Subtraction**

In [33]:
k = np.matrix('1 2 3 4; 5 6 7 8')
j = np.matrix('4 5 9 10; 3 5 2 7')

sum = k+j
diff = k-j


In [34]:
print (sum)

[[ 5  7 12 14]
 [ 8 11  9 15]]


In [35]:
print (diff)

[[-3 -3 -6 -6]
 [ 2  1  5  1]]


**Matrix Multiplication**

In order to multiply two matrices, *no. of columns in the first matrix = no. of rows in the second matrix*

In [36]:
print (k*j)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [37]:
s1 = np.matrix('2 3; 4 2') #2x2 order
s2 = np.matrix('1 5; 2 8') #2X2 order
print (s1*s2)

[[ 8 34]
 [ 8 36]]


In [38]:
print (np.dot(s1,s2)) #same result

[[ 8 34]
 [ 8 36]]


**Inverse of a Matrix**

In [43]:
inverse1= np.linalg.inv(s1)
print (inverse1)

[[-0.25   0.375]
 [ 0.5   -0.25 ]]


**Determinant of a Matrix**

In [45]:
determinants1 = np.linalg.det(s1)
print (determinants1)

-7.999999999999998
