<a href="https://colab.research.google.com/github/PrashantSBasnet/L3_Sem2/blob/master/Week7/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr1 = np.array([

                 [1,2,3,4,5,6],
                 [4,5,6,7,8,9]

        ])

In [4]:
print (arr1)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [5]:
print (arr1.shape)

(2, 6)


In [6]:
arr2 = arr1.flatten() #converting into 1D array
print(arr2)

[1 2 3 4 5 6 4 5 6 7 8 9]


In [7]:
arr3 = arr1.reshape(3,4) #3 Rows and 4 Columns
print (arr3)  #2d array created

[[1 2 3 4]
 [5 6 4 5]
 [6 7 8 9]]


In [8]:
print (arr1.size)

12


In [9]:
#3D array with dimensions 2x2x3, denoting a shape where the array consists of 2 matrices, each matrix containing 2 rows and 3 columns.
arr4 = arr1.reshape(2,2,3) #creating 3D array. since 12 elements the product = 12
print (arr4)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


**Matrices**

 A matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as * (matrix multiplication) and ** (matrix power).

Suppose x is  a 2 dimensional array.

In [10]:
x = np.array ([
              [2,3,4,5,6],
              [7,8,9,10,11]
])

In [11]:
m = np.matrix(x)
print (m)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]


In [12]:
m = np.matrix('1 2 3 4; 5,6,7,8')
print (m)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
m2 = np.matrix('1 2 3; 5,6,7; 8,9,10')
print (m2)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]


In [14]:
print (np.diagonal(m2))

[ 1  6 10]


In [15]:
print (m.min())

1


**Matrix Addition and Subtraction**

In [16]:
k = np.matrix('1 2 3 4; 5 6 7 8')
j = np.matrix('4 5 9 10; 3 5 2 7')

sum = k+j
diff = k-j


In [17]:
print (sum)

[[ 5  7 12 14]
 [ 8 11  9 15]]


In [18]:
print (diff)

[[-3 -3 -6 -6]
 [ 2  1  5  1]]


**Matrix Multiplication**

In order to multiply two matrices, *no. of columns in the first matrix = no. of rows in the second matrix*

In [23]:
s1 = np.matrix('2 3; 4 2') #2x2 order
s2 = np.matrix('1 5; 2 8') #2X2 order


In [24]:
print (np.dot(s1,s2)) #matrix multiplication

[[ 8 34]
 [ 8 36]]


In [28]:
#Element wise multiplication. This is not matrix Multiplication
print (s1*s2)



[[ 8 34]
 [ 8 36]]


In [29]:
#each element is multiplied by 2
print (2 * s1)

[[4 6]
 [8 4]]


**Array multiplication is not matrix multiplication:**

In [30]:
c = np.ones((3, 3))
print(c * c) # NOT matrix multiplication!

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Inverse of a Matrix**

In [ ]:
inverse1= np.linalg.inv(s1)
print (inverse1)

[[-0.25   0.375]
 [ 0.5   -0.25 ]]


**Determinant of a Matrix**

In [ ]:
determinants1 = np.linalg.det(s1)
print (determinants1)

-7.999999999999998


**Creating Matrices**

In [31]:
#Zero Matrix
b = np.zeros((3, 3)) #zero matrix
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:

a = np.ones((3, 3)) # reminder: (3, 3) is a tuple
print(a)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
#Unit Matrix (Identity Matrix)
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
#Diagonal Matrix
d = np.diag(np.array([11, 27, 34, 4]))
print(d)

[[11  0  0  0]
 [ 0 27  0  0]
 [ 0  0 34  0]
 [ 0  0  0  4]]


**Random Numbers**

In [42]:
a = np.random.rand(70) # uniform in [0, 1]
print(a)

[0.81546143 0.70685734 0.72900717 0.77127035 0.07404465 0.35846573
 0.11586906 0.86310343 0.62329813 0.33089802 0.06355835 0.31098232
 0.32518332 0.72960618 0.63755747 0.88721274 0.47221493 0.11959425
 0.71324479 0.76078505 0.5612772  0.77096718 0.4937956  0.52273283
 0.42754102 0.02541913 0.10789143 0.03142919 0.63641041 0.31435598
 0.50857069 0.90756647 0.24929223 0.41038292 0.75555114 0.22879817
 0.07697991 0.28975145 0.16122129 0.92969765 0.80812038 0.63340376
 0.87146059 0.80367208 0.18657006 0.892559   0.53934224 0.80744016
 0.8960913  0.31800347 0.11005192 0.22793516 0.42710779 0.81801477
 0.86073058 0.00695213 0.5107473  0.417411   0.22210781 0.11986537
 0.33761517 0.9429097  0.32320293 0.51879062 0.70301896 0.3636296
 0.97178208 0.96244729 0.2517823  0.49724851]


In [39]:
b = np.random.randn(70) # Gaussian
print(b)

[ 2.43050037 -0.34504869 -0.57872236  0.19791503 -1.47417097 -0.16820076
  1.04519277 -0.81242629 -0.42488617 -0.24551712  1.32339927  1.00155345
 -0.56152418  0.56452009  0.68608127 -0.3566382   0.13402371  1.37333789
  0.57446388 -0.47799766 -0.2894187   0.57711924 -0.43314138 -1.01341292
 -0.47086056 -0.80418848 -1.29715181  1.20290956  0.24942786 -1.26248195
  0.54004535  1.20795776  1.10340822  1.50647027 -0.15640565 -0.58020303
 -0.10015221 -0.02190008  2.04128692 -1.93375832  0.73970055  0.7044686
 -0.60766771 -1.06630845 -0.22243767  0.80872165 -0.59177045 -1.03969272
 -0.89835458  0.25617361  1.71307599 -0.52600076  0.73000533  1.8721468
 -0.5182681  -0.19374509 -0.88172809  1.1649057  -1.14920249 -0.39015215
  0.39975072 -0.62050586  0.38664775  0.19140014 -0.14046973 -1.9185332
  0.30057689  0.223999   -2.03175575 -0.2641715 ]


In [47]:
#useful in situations where you want to debug or share your code with others, ensuring they obtain the same results
np.random.seed(42) # Setting the random seed
b = np.random.rand(3)
print(b)

[0.37454012 0.95071431 0.73199394]
