<a href="https://colab.research.google.com/github/PrashantSBasnet/L3_Sem2/blob/master/Week7/NumPyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 - pip install numpy

import numpy as np

print(np.__version__)



**Why are Lists slower?**
*   Lists are slower than Numpy.
*   Lists uses built in int type that consists of: Size, Reference Count, Object Type, Object Value
*   Type checking is necessary when iterating though the objects stored in a list.
*   List doesn't use contiguous memeory.

**Why is NumPy faster?**
*   It uses fixed type. NumPy uses less bytes of memory which is faster to read.
*   No type checking when iterating throught the objects
*   NumPy uses contiguous memory.









**Applications of NumPy**


*   Mathematics (MATLAB Replacement)
*   Plotting (Matplotlib)
*   Backend of the libraries: Pandas, Connect 4, Digital Photography
*   Machine Learning




Array is a container that holds multiple values of the same type.

In [2]:
import numpy as np

In [3]:
a= np.array([1,2,3]) #1D Array
print (a)

[1 2 3]


In [4]:
b = np.array([[1,2,3],[3.0,4.0,8.6]]) #2D Array
b1 = np.array([[1,2,3,4,6]]) #2d Array
print (b)

[[1.  2.  3. ]
 [3.  4.  8.6]]


In [5]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3D Array
c1 = np.array([[[1,2,3,4,5]]]) #3D Array
print (c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
#Get Dimension
a.ndim

1

In [7]:
b.ndim


2

In [8]:
b1.ndim

2

In [9]:
c.ndim

3

In [10]:
c1.ndim

3

In [11]:
#GetShape
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [13]:
b1.shape

(1, 5)

In [14]:
c.shape

(2, 2, 3)

In [15]:
c1.shape

(1, 1, 5)

In [16]:
# Get type
a.dtype

dtype('int64')

In [17]:
x = np.array([1,2,3], dtype= 'int64')
x.dtype

dtype('int64')

In [18]:
x.itemsize #memory consumed by datatype

8

In [19]:
#no. of elements
x.size

3

In [20]:
print(c)
print("Shape:", c.shape)
print("Number of dimensions:", c.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Number of dimensions: 3


In [21]:
print(c1)
print("Shape:", c1.shape)
print("Number of dimensions:", c1.ndim)

[[[1 2 3 4 5]]]
Shape: (1, 1, 5)
Number of dimensions: 3


**Functions to create Array**

**using linspace()**


*   Return evenly spaced numbers over a specified interval.
*   Returns num evenly spaced samples, calculated over the interval [start, stop]. In other words, the samples are uniformly distributed in linear space
*   The endpoint of the interval can optionally be excluded.

**numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)**









In [22]:
from numpy import *

In [23]:
arr = linspace(2,3,num=5)
print (arr)

[2.   2.25 2.5  2.75 3.  ]


In [24]:
arr = linspace(2,3,7)
print (arr)

[2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.        ]


**Using arange()**
*   Similar to linspace, with the step size specified instead of the number of samples.




In [25]:
arr = arange(1,10,3)   #arange(start,stop,step)
print(arr)

[1 4 7]


**Using logspace()**
*   Return numbers spaced evenly on a log scale.
*   In linear space, the sequence starts at base ** start (base to the power of start) and ends with base ** stop

In [26]:
arr = logspace(4, 10, 5)
print (arr)

[1.00000000e+04 3.16227766e+05 1.00000000e+07 3.16227766e+08
 1.00000000e+10]


In [27]:
print ('%.2f' %arr[3])

316227766.02


**Using zeros()**

In [28]:
arr = zeros(2) #size is specified
print (arr)

[0. 0.]


**Using ones()**

In [29]:
arr = ones(5) #size is specified
print (arr)

[1. 1. 1. 1. 1.]


**Statistics**

In [1]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
print(x.mean())
print(np.median(x))
print(y)
print(np.median(y,axis=-1)) # last axis
print(x.std()) # full population standard dev.
print(x.cumsum())

NameError: name 'np' is not defined