<a href="https://colab.research.google.com/github/PrashantSBasnet/L3_Sem2/blob/master/Week6/Array_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np


In [13]:
arr = np.array([1,2,4,5,6,7])
arr = arr + 5
print (arr)


[ 6  7  9 10 11 12]


In [14]:
arr1= np.array([1,2,4,5,6,7])
arr2= np.array([3,4,5,6,7,8])
sum = arr1+arr2
print (sum)

[ 4  6  9 11 13 15]


In [15]:
product = arr1 * arr2
print (product)

[ 3  8 20 30 42 56]


In [23]:
arr = np.array([7, 3, 2, 5, 8, 1])
arr3 = np.array([3,4,5,6,6,2])
#print(np.sum(arr))
#print(np.min(arr))
#print(np.sin(arr))
#print(np.sqrt(arr))
#print(np.sort(arr))
#print(np.concatenate([arr,arr3]))

[7 3 2 5 8 1 3 4 5 6 6 2]


**Aliasing**


*   Creating a new reference to an existing array, rather than copying its contents.
*   The changes made to the alias will affect the original array as well.



In [59]:
sampleArr1 = np.array([3,5,6,8,3])
sampleArr2 = sampleArr1
print (sampleArr1)
print (sampleArr2)

#making some changes
sampleArr2[0]= 99

print (sampleArr1)
print (sampleArr2)

[3 5 6 8 3]
[3 5 6 8 3]
[99  5  6  8  3]
[99  5  6  8  3]


In [73]:
#printing memory address
#both arrays point to the same address
print ("Memory location of sampleArr1:", id(sampleArr1))
print ("Memory location of sampleArr2:", id(sampleArr2))

Memory location of sampleArr1: 139377482999312
Memory location of sampleArr2: 139377482999312


**View**



*   View is just a view of the original array.
*   A new way of looking at the data by changing certain metadata and these new arrays are called views



In [68]:
sampArr = np.array([1,2,3,4,5,6])
copyArr = sampArr.view()
sampArr[0] = 32

#modifying samArr doesn't affect copyArr
print ("samArr:", sampArr)
print ("copyArr:", copyArr)

#different memory location
print ("Memory location of sampArr:", id(sampArr))
print ("Memory location of copyArr:", id(copyArr))

samArr: [32  2  3  4  5  6]
copyArr: [32  2  3  4  5  6]
Memory location of sampArr: 139377481345392
Memory location of copyArr: 139377481649776


**Copy**


*   When a new array is created by duplicating the data buffer as well as the metadata, it is called a copy.
*   Changes made to the copy do not reflect on the original array.
*   Making a copy is slower and memory-consuming but sometimes necessary.



In [71]:
sampArr = np.array([1,2,3,4,5,6])
copyArr = sampArr.copy()
sampArr[0] = 32

print ("sampArr:" , sampArr)
print ("copyArr:", copyArr)

print ("sampArr:", sampArr)

#creates in different memory location
print ("Memory location of sampArr:", id(sampArr))
print ("Memory location of copyArr:",id(copyArr))

sampArr: [32  2  3  4  5  6]
copyArr: [1 2 3 4 5 6]
sampArr: [32  2  3  4  5  6]
Memory location of sampArr: 139377481500592
Memory location of copyArr: 139377483327184


**Array Slicing**
*   Access the portion of an array using the slicing operator :






In [74]:
# create a 1D array
array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])

# slice array1 from index 2 to index 6 (exclusive)
print(array1[2:6])  # [5 7 8 9]

# slice array1 from index 0 to index 8 (exclusive) with a step size of 2
print(array1[0:8:2])  # [1 5 8 2]

# slice array1 from index 3 up to the last element
print(array1[3:])  # [7 8 9 2 4 6]

# items from start to end
print(array1[:])   # [1 3 5 7 8 9 2 4 6]

[5 7 8 9]
[1 5 8 2]
[7 8 9 2 4 6]
[1 3 5 7 8 9 2 4 6]


In [80]:
# 1. Using start Parameter
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify elements from index 3 onwards
numbers[3:] = 20
print(numbers)

[ 2  4  6 20 20 20]


In [79]:
#2. Using stop Parameter
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify the first 3 elements
numbers[:3] = 40
print(numbers)

[40 40 40  8 10 12]


In [78]:
#3. Using start and stop parameter
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify elements from indices 2 to 5
numbers[2:5] = 22
print(numbers)

# Output: [2 4 22 22 22 12]

[ 2  4 22 22 22 12]


In [77]:
#4. Using start, stop, and step parameter
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify every second element from indices 1 to 5
numbers[1:5:2] = 16
print(numbers)

[ 2 16  6 16 10 12]


In [81]:
#NumPy Array Negative Slicing
import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# slice the last 3 elements of the array
# using the start parameter
print(numbers[-3:])    # [8 10 12]

# slice elements from 2nd-to-last to 4th-to-last element
# using the start and stop parameters
print(numbers[-5:-2])    # [4 6 8]

# slice every other element of the array from the end
# using the start, stop, and step parameters
print(numbers[-1::-2])   # [12 8 4]

[ 8 10 12]
[4 6 8]
[12  8  4]


In [82]:
#Reverse NumPy Array Using Negative Slicing
import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# generate reversed array
reversed_numbers = numbers[::-1] #Here, the slice numbers[::-1] selects all the elements of the array with a step size of -1, which reverses the order of the elements.
print(reversed_numbers)

[12 10  8  6  4  2]


**2D NumPy Array Slicing**

Syntax: array[row_start:row_stop:row_step, col_start:col_stop:col_step]

In [83]:
# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                   [9, 11, 13, 15]])

print(array1[:2, :2])

[[ 1  3]
 [ 9 11]]


In [84]:
# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])


# slice the array to get the first two rows and columns
subarray1 = array1[:2, :2]

# slice the array to get the last two rows and columns
subarray2 = array1[1:3, 2:4]

# print the subarrays
print("First Two Rows and Columns: \n",subarray1)
print("Last two Rows and Columns: \n",subarray2)

First Two Rows and Columns: 
 [[ 1  3]
 [ 9 11]]
Last two Rows and Columns: 
 [[13 15]
 [ 6  8]]




*   array1[:2, :2] - slices array1 that starts at the first row and first column (default values), and ends at the second row and second column (exclusive)
*   array1[1:3, 2:4] - slices array1 that starts at the second row and third column (index 1 and 2), and ends at the third row and fourth column (index 2 and 3)





1.   We slice array1 to get the first two rows and first two columns. We use slicing notation [:2, :2] where :2 selects the first two rows and :2 selects the first two columns:
2.   We slice array1 to get the last two rows and last two columns. We use slicing notation [1:3, 2:4] where 1:3 selects rows 1 and 2, and 2:4 selects columns 2 and 3:



**Indexing** can be done in numpy by using an array as an index. In case of slice, a view or shallow copy of the array is returned but in index array a copy of the original array is returned. Numpy arrays can be indexed with other arrays or any other sequence with the exception of tuples. The last element is indexed by -1 second last by -2 and so on.

In [85]:
# Python program to demonstrate
# the use of index arrays.
import numpy as np

# Create a sequence of integers from
# 10 to 1 with a step of -2
a = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",a)

# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]
